### ISSUE TITLE
[DOCS] How to import existing resources?

### ISSUE THREAD

**Issue by boldandbusted** [scalefactory/terraform-tfe-workspaces#6]
Howdy. I'd like to import existing TFE/TFC workspaces into Terraform while using this module. Any guides or examples on how to properly perform imports? Thanks for this module! Cheers! :)

**Comment by mbevc1** [comment]
Hi @boldandbusted ! It'd probably depend on what do you want to import. Without any additional context I'd suggest checking the provider syntax for importing resources you currently have, i.e. for the workspace: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#import

Make sure you prefix the resources with the module path and include all resources involved, such as variables: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable. You cna gradually test what's already in the state and what's missing using intermediate `plan`s.

**Comment by mbevc1** [comment]
Seems this answers your question and I'll close this issue now.
